# CLion remote docker environment
#
# Build:
#     docker build -t igang/build-clion-cpp-env -f Dockerfile-build-clion .
#
# Run:
#     docker run --rm -d --cap-add sys_ptrace -p 2222:22 --name build_clion_remote_env igang/build-clion-cpp-env
#
# ssh credentials (test user):
#     user@password
#
# Clear local ssh host key cache:
#     ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222" # optional
#
# Stop:
#     docker stop build_clion_remote_env
#

FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
# Europe/Helsinki
ENV TZ=Europe/Rome

RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    gdb \
    cmake \
	&& rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    # libtins requirements
    libpcap-dev \
    # libssl-dev \
    # END: libtins requirements
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    ssh \
	&& rm -rf /var/lib/apt/lists/*

RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_clion \
  && mkdir /run/sshd

RUN useradd -m user \
  && yes password | passwd user

EXPOSE 22

# -D: do not demonize
# -e: writes logs to std error
# -f: config file
CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_clion"]
