#ifndef BGP_SIMULATION_CONFIGURATION_PARSER_PARSERNETWORKCARD_H
#define BGP_SIMULATION_CONFIGURATION_PARSER_PARSERNETWORKCARD_H

vector<NetworkCard*>* parseAndBuildNetworkCards(
    const YAML::Node& networkCards_yaml);

#endif  // BGP_SIMULATION_CONFIGURATION_PARSER_PARSERNETWORKCARD_H
