---
routers:
  - id: R1
    AS_number: 1
    networkCard:
      - interface: eth0
        IP: 90.36.25.1
        netmask: 255.255.0.0
      - interface: eth1
        IP: 85.90.20.1
        netmask: 255.255.0.0
    peers: [ 85.90.20.2 ]

  - id: R2
    AS_number: 2
    default_gateway: 85.90.20.1
    networkCard:
      - interface: eth0
        IP: 26.37.3.2
        netmask: 255.255.0.0
      - interface: eth5
        IP: 85.90.20.2
        netmask: 255.255.0.0
    peers: [ 85.90.20.1 ]

clients:
  - id: E1
    default_gateway: 90.36.25.1
    networkCard:
      - interface: eth0
        IP: 90.36.25.123
        netmask: 255.255.0.0
  - id: E2
    default_gateway: 26.37.3.2
    networkCard:
      - interface: eth0
        IP: 26.37.3.1
        netmask: 255.255.0.0

links:
  - device_ids: [R1, E1]
    device_source_interfaces: [eth0, eth0]
    connection_status: active
  - device_ids: [R2, E2]
    device_source_interfaces: [eth0, eth0]
    connection_status: active
  - device_ids: [R1, R2]
    device_source_interfaces: [eth1, eth5]
    connection_status: active
...
