---
# Topology
# E1 <--> R1 <-------------> R2 <--> E2
#         ^                  ^
#         '--> R5 <--> R3 <--'
#              ^^      ^
#              ||      '--> R4 <--> E4
#              ||           ^
#              ||           |
#              ||           v
#              |'---------> R6
#            /              ^
#           |               |
#           |               v
#           '-> R8 <------> R7
#               ^           ^
#               |           |
#               v           v
#               R9 <-----> R10

# Logic behind the IPs assignment:
#
# aa.bb.0.0 is the network between the two routers Ra and Rb where a<b
# the IPs are assigned with this schema aa.bb.0.x
#   where:
#     - a match the lowest router ID number
#     - b match the highest router ID number
#     - x match the router ID number
#   e.g.
#     - 11.33.0.1 R1 (toward R3)
#     - 22.33.0.2 R2 (toward R3)
#     - 11.33.0.3 R3 (toward R1)
#     - 22.33.0.3 R3 (toward R2)
#
# 199.x.0.0 is the network between the endpoints and the routers
# the IPs for the routers are assigned with this schema 199.x.0.x
# the IPs for the endpoints are assigned with this schema 199.x.0.10y
#   where:
#     - x match the router ID number
#     - y match the endpoint ID number
#   e.g.
#     - 199.1.0.1   R1 (toward E1)
#     - 199.2.0.2   R2 (toward E2)
#     - 199.1.0.101 E1 (toward R1)
#     - 199.2.0.102 E2 (toward R2)

routers:
  - id: R1
    AS_number: 1
    networkCard:
      - interface: lan1
        IP: 199.1.0.1
        netmask: 255.255.0.0
      - interface: eth2
        IP: 11.22.0.1
        netmask: 255.255.0.0
      - interface: eth5
        IP: 11.55.0.1
        netmask: 255.255.0.0
    peers: [ 11.22.0.2, 11.55.0.5 ]

  - id: R2
    AS_number: 2
    default_gateway: 22.33.0.3
    networkCard:
      - interface: lan2
        IP: 199.2.0.2
        netmask: 255.255.0.0
      - interface: eth1
        IP: 11.22.0.2
        netmask: 255.255.0.0
      - interface: eth3
        IP: 22.33.0.2
        netmask: 255.255.0.0
    peers: [ 11.22.0.1, 22.33.0.3 ]

  - id: R3
    AS_number: 3
    default_gateway: 33.55.0.5
    networkCard:
      - interface: eth5
        IP: 33.55.0.3
        netmask: 255.255.0.0
      - interface: eth2
        IP: 22.33.0.3
        netmask: 255.255.0.0
      - interface: eth4
        IP: 33.44.0.3
        netmask: 255.255.0.0
    peers: [ 33.55.0.5, 22.33.0.2, 33.44.0.4 ]

  - id: R4
    AS_number: 4
    networkCard:
      - interface: lan4
        IP: 199.4.0.4
        netmask: 255.255.0.0
      - interface: eth3
        IP: 33.44.0.4
        netmask: 255.255.0.0
      - interface: eth6
        IP: 44.66.0.4
        netmask: 255.255.0.0
    peers: [ 33.44.0.3, 44.66.0.6 ]

  - id: R5
    AS_number: 5
    networkCard:
      - interface: eth1
        IP: 11.55.0.5
        netmask: 255.255.0.0
      - interface: eth3
        IP: 33.55.0.5
        netmask: 255.255.0.0
      - interface: eth6
        IP: 55.66.0.5
        netmask: 255.255.0.0
      - interface: eth8
        IP: 55.88.0.5
        netmask: 255.255.0.0
    peers: [ 11.55.0.1, 33.55.0.3, 55.66.0.6, 55.88.0.8 ]

  - id: R6
    AS_number: 6
    networkCard:
      - interface: eth4
        IP: 44.66.0.6
        netmask: 255.255.0.0
      - interface: eth5
        IP: 55.66.0.6
        netmask: 255.255.0.0
      - interface: eth7
        IP: 66.77.0.6
        netmask: 255.255.0.0
    peers: [ 44.66.0.4, 55.66.0.5, 66.77.0.7 ]

  - id: R7
    AS_number: 7
    networkCard:
      - interface: eth6
        IP: 66.77.0.7
        netmask: 255.255.0.0
      - interface: eth8
        IP: 77.88.0.7
        netmask: 255.255.0.0
      - interface: eth10
        IP: 77.10.0.7
        netmask: 255.255.0.0
    peers: [ 66.77.0.6, 77.88.0.8, 77.10.0.10 ]

  - id: R8
    AS_number: 8
    networkCard:
      - interface: eth5
        IP: 55.88.0.8
        netmask: 255.255.0.0
      - interface: eth7
        IP: 77.88.0.8
        netmask: 255.255.0.0
      - interface: eth9
        IP: 88.99.0.8
        netmask: 255.255.0.0
    peers: [ 55.88.0.5, 77.88.0.7, 88.99.0.9 ]

  - id: R9
    AS_number: 9
    networkCard:
      - interface: eth8
        IP: 88.99.0.9
        netmask: 255.255.0.0
      - interface: eth10
        IP: 99.10.0.9
        netmask: 255.255.0.0
    peers: [ 88.99.0.8, 99.10.0.10 ]

  - id: R10
    AS_number: 10
    networkCard:
      - interface: eth7
        IP: 77.10.0.10
        netmask: 255.255.0.0
      - interface: eth9
        IP: 99.10.0.10
        netmask: 255.255.0.0
    peers: [ 77.10.0.7, 99.10.0.9 ]

clients:
  - id: E1
    default_gateway: 199.1.0.1
    networkCard:
      - interface: wifi1
        IP: 199.1.0.101
        netmask: 255.255.0.0
  - id: E2
    default_gateway: 199.2.0.2
    networkCard:
      - interface: wifi2
        IP: 199.2.0.102
        netmask: 255.255.0.0
  - id: E4
    default_gateway: 199.4.0.4
    networkCard:
      - interface: wifi4
        IP: 199.4.0.104
        netmask: 255.255.0.0

links:
  - device_ids: [ R1, E1 ]
    device_source_interfaces: [ lan1, wifi1 ]
    connection_status: active
  - device_ids: [ R2, E2 ]
    device_source_interfaces: [ lan2, wifi2 ]
    connection_status: active
  - device_ids: [ R4, E4 ]
    device_source_interfaces: [ lan4, wifi4 ]
    connection_status: active

  - device_ids: [ R1, R2 ]
    device_source_interfaces: [ eth2, eth1 ]
    connection_status: active
  - device_ids: [ R1, R5 ]
    device_source_interfaces: [ eth5, eth1 ]
    connection_status: active
  - device_ids: [ R2, R3 ]
    device_source_interfaces: [ eth3, eth2 ]
    connection_status: active
  - device_ids: [ R3, R4 ]
    device_source_interfaces: [ eth4, eth3 ]
    connection_status: active
  - device_ids: [ R3, R5 ]
    device_source_interfaces: [ eth5, eth3 ]
    connection_status: active
  - device_ids: [ R4, R6 ]
    device_source_interfaces: [ eth6, eth4 ]
    connection_status: active
  - device_ids: [ R5, R6 ]
    device_source_interfaces: [ eth6, eth5 ]
    connection_status: active
  - device_ids: [ R5, R8 ]
    device_source_interfaces: [ eth8, eth5 ]
    connection_status: active
  - device_ids: [ R6, R7 ]
    device_source_interfaces: [ eth7, eth6 ]
    connection_status: active
  - device_ids: [ R7, R8 ]
    device_source_interfaces: [ eth8, eth7 ]
    connection_status: active
  - device_ids: [ R7, R10 ]
    device_source_interfaces: [ eth10, eth7 ]
    connection_status: active
  - device_ids: [ R8, R9 ]
    device_source_interfaces: [ eth9, eth8 ]
    connection_status: active
  - device_ids: [ R9, R10 ]
    device_source_interfaces: [ eth10, eth9 ]
    connection_status: active
...
