---
# Topology
# E1 <--> R1 <--> R2 <--> E2

# Logic behind the IPs assignment:
#
# aa.bb.0.0 is the network between the two routers Ra and Rb where a<b
# the IPs are assigned with this schema aa.bb.0.x
#   where:
#     - a match the lowest router ID number
#     - b match the highest router ID number
#     - x match the router ID number
#   e.g.
#     - 11.33.0.1 R1 (toward R3)
#     - 22.33.0.2 R2 (toward R3)
#     - 11.33.0.3 R3 (toward R1)
#     - 22.33.0.3 R3 (toward R2)
#
# 199.x.0.0 is the network between the endpoints and the routers
# the IPs for the routers are assigned with this schema 199.x.0.x
# the IPs for the endpoints are assigned with this schema 199.x.0.10y
#   where:
#     - x match the router ID number
#     - y match the endpoint ID number
#   e.g.
#     - 199.1.0.1   R1 (toward E1)
#     - 199.2.0.2   R2 (toward E2)
#     - 199.1.0.101 E1 (toward R1)
#     - 199.2.0.102 E2 (toward R2)

routers:
  - id: R1
    AS_number: 1
    networkCard:
      - interface: eth0
        IP: 199.1.0.1
        netmask: 255.255.0.0
      - interface: eth1
        IP: 11.22.0.1
        netmask: 255.255.0.0
    peers: [ 11.22.0.2 ]

  - id: R2
    AS_number: 2
    default_gateway: 11.22.0.1
    networkCard:
      - interface: eth0
        IP: 199.2.0.2
        netmask: 255.255.0.0
      - interface: eth5
        IP: 11.22.0.2
        netmask: 255.255.0.0
    peers: [ 11.22.0.1 ]

clients:
  - id: E1
    default_gateway: 199.1.0.1
    networkCard:
      - interface: eth0
        IP: 199.1.0.101
        netmask: 255.255.0.0
  - id: E2
    default_gateway: 199.2.0.2
    networkCard:
      - interface: eth0
        IP: 199.2.0.102
        netmask: 255.255.0.0

links:
  - device_ids: [R1, E1]
    device_source_interfaces: [eth0, eth0]
    connection_status: active
  - device_ids: [R2, E2]
    device_source_interfaces: [eth0, eth0]
    connection_status: active
  - device_ids: [R1, R2]
    device_source_interfaces: [eth1, eth5]
    connection_status: active
...
